// Interface glass only. These controls are independent from the Three.js wordmark.
export const uiGlass = {
  mapSize: 512,
  inkHysteresis: .18,
  tint: .035,
  menuTint: .08,
  menuBackdropOpacity: .48,
  blur: .75,
  menuBlur: 2,
  fallbackBlur: 2,
  fallbackMenuBlur: 4,
  saturation: 1.08,
  strength: .092,
  menuStrength: .04,
  dispersion: .035,
  depth: .88,
  curvature: .3,
  bend: .68,
  bendWidth: .38,
  sheen: .6,
  sheenWidth: 1.8,
  sheenAngle: 125,
  sheenFalloff: 1.65,
  glow: .045,
  glowSpread: .4,
  glowFalloff: 1.6,
  specular: .82,
  pressScale: .97,
  pressDuration: 140,
  rippleDuration: 460,
  selectionDuration: 220,
} as const;
