import React from 'react';
import ReactDOM from 'react-dom/client';
import { NextPortfolio } from './Portfolio';
import 'lenis/dist/lenis.css';
import './styles.css';
import './liquidSurface.css';
import './meteors.css';
import './background.css';
import { analytics } from '../shared/analytics/client';
import { AnalyticsConsent } from '../shared/analytics/Consent';
const collectorOrigin = import.meta.env.VITE_ANALYTICS_COLLECTOR_ORIGIN ?? '';
analytics.configure('portfolio', collectorOrigin ? `${collectorOrigin.replace(/\/+$/, '')}/v1/events` : '', import.meta.env.VITE_ANALYTICS_ENABLED === 'true' && !location.pathname.startsWith('/zh/'), import.meta.env.VITE_ANALYTICS_CAMPAIGN_TAGS ?? '');
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><NextPortfolio /><AnalyticsConsent surface="portfolio" /></React.StrictMode>);
