import type { HarvardChapter, HarvardMedia } from '../harvardCaseTypes';

const asset = (id: string, sourceNode: string, image: string, width: number, height: number, alt: string): HarvardMedia => ({
  id, sourceNode, image, width, height, alt,
});

const aiLogicDiagram: HarvardMedia = { ...asset(
  'psytrain-ai-logic-diagram',
  '344:3643',
  '/v2-3/cases/psytrain/avatar-ai-logic-themed.png',
  4896,
  3168,
  'Complete AI Logic and Emotion-to-Face Expression Mapping infographic: five layers with left and right explanations, original connecting curves, and all seven avatar expressions',
), background: 'transparent' };


const landingScreen = asset('psytrain-ui-landing', '190:10719', '/v2-3/cases/psytrain/ui-landing-screen.png', 3960, 2160, 'PsytrAIn landing page interface with Emma and selectable patient cards');
const trainingScreen = asset('psytrain-ui-training', '190:10733', '/v2-3/cases/psytrain/ui-training-screen.png', 3960, 2160, 'PsytrAIn training screen with Emma, conversation, and Help panels');
const resultScreen = asset('psytrain-ui-result', '190:10720', '/v2-3/cases/psytrain/ui-result-screen.png', 3960, 2160, 'PsytrAIn result screen with session evaluation and level metrics');
const navigationFlow: HarvardMedia = { ...asset('psytrain-ui-navigation-flow', '344:4550', '/v2-3/cases/psytrain/ui-navigation-flowchart-transparent.svg', 832, 1488, 'Vertical UI flow chart showing navigation branches and merges'), background: 'transparent' };
const liveEmotionAvatar = asset('psytrain-ui-live-emotion-avatar', '190:10734', '/v2-3/cases/psytrain/ui-live-emotion-avatar.png', 2752, 1536, 'Translucent blue Emma avatar with a facial and body signal overlay');

export const psytrainAvatarUIChapters: HarvardChapter[] = [
  {
    id: 'character',
    sourceFrame: '159:4979',
    title: 'Character',
    sections: [
      {
        id: 'ai-logic-layers',
        title: 'AI Logic',
        layout: 'wide',
        media: [aiLogicDiagram],
        sourceNodes: ['159:5122', '159:5719', '159:5746', '159:5757', '159:5768', '159:5115', '159:5116', '159:5086', '159:5089', '159:5092', '159:5095', '159:5098', '159:5101', '159:5104'],
        transcript: [
          { title: 'Cognitive Output', body: ['Responses are generated by conditioning language models on identity and affect states.', 'Synthesized output that reflects memory, identity, and context-aware decision-making.'], sourceNodes: ['159:5121', '159:5770', '159:5774'] },
          { title: 'Facial and Animation control', body: ['Emotion vectors are mapped to blendshape weights and viseme sequences for output.', 'Emotion output drives blendshape weights and visemes for animated avatar responses.'], sourceNodes: ['159:5120', '159:5769', '159:5773'] },
          { title: 'Speaking Emotion', body: ['Prosodic contours are analyzed to estimate arousal, valence, and intent signals.', 'Speech tone and prosody analyzed to detect emotional intent and energy level.'], sourceNodes: ['159:5119', '159:5767', '159:5772'] },
          { title: 'Form Personality', body: ['Behavioral patterns are clustered to construct a latent identity embedding.', 'Traits and patterns extracted from behavior to generate a responsive digital persona.'], sourceNodes: ['159:5118', '159:5766', '159:5771'] },
          { title: 'Patient Data', body: ['Sentences are parsed into linguistic and acoustic features for multimodal input processing.', 'Raw sensory data including voice, video, and behavioral traces collected in real time.'], sourceNodes: ['159:5117', '159:5765', '159:5775'] },
          { title: 'Emotion-to-Face Expression Mapping', body: ['During interaction, the AI continuously analyzes the emotional content of its own generated speech—detecting intent, tone, and affective shifts in real time. These internal emotional states are then transmitted to a 3D avatar via parametric controls, triggering corresponding blendshape activations. As a result, the avatar dynamically reflects the AI’s current emotional tone on its face, enabling more humanlike, expressive, and believable communication.'], sourceNodes: ['159:5115','159:5116'] },
          { title: 'Expressions', body: ['Happy · Contempt · Normal · Surprise · Anger · Sad · Disgust'], sourceNodes: ['159:5088','159:5091','159:5094','159:5097','159:5100','159:5103','159:5106'] },
        ],
      },

    ],
  },
  {
    id: 'ui',
    sourceFrame: '190:10717',
    title: 'UI',
    sections: [
      {
        id: 'ui-training-screens',
        title: 'UI Design',
        layout: 'steps',
        sourceNodes: ['I190:10732;48:417', '190:10719', '190:10720', '190:10733'],
        items: [
          { title: 'Landing Page', body: ['Select Training'], media: landingScreen, sourceNodes: ['190:10719', '190:10725', '190:10730'] },
          { title: 'Training Section', body: ['End Training', 'Ask for Help'], media: trainingScreen, sourceNodes: ['190:10733', '190:10729', '190:10731', '190:10744'] },
          { title: 'Result Screen', body: ['Back to Landing Page'], media: resultScreen, sourceNodes: ['190:10720', '190:10727', '190:10741'] },
        ],
      },
      {
        id: 'ui-live-avatar',
        title: 'Live Emotional reaction',
        layout: 'split',
        body: ['Live Body Language'],
        media: [liveEmotionAvatar],
        sourceNodes: ['190:10734', '190:10781', '190:10782'],
      },
      {
        id: 'ui-navigation-flow',
        title: 'Flow Chart',
        layout: 'steps',
        media: [navigationFlow],
        sourceNodes: ['190:10747', '190:10748', '190:10749', '190:10763', '190:10765', '190:10767', '190:10769', '190:10771', '190:10772', '190:10774', '190:10776', '190:10777', '190:10779'],
        items: [
          { title: 'Log in / Sign Up', sourceNodes: ['190:10764'] },
          { title: 'Landing Page', sourceNodes: ['190:10766'] },
          { title: 'Patient(Emma) · Patients', sourceNodes: ['190:10778', '190:10780'] },
          { title: 'Training Section', sourceNodes: ['190:10768'] },
          { title: 'Transcript · Help', sourceNodes: ['190:10773', '190:10775'] },
          { title: 'Result Screen', sourceNodes: ['190:10770'] },
        ],
      },
    ],
  },
];
