// Generated by the local PsytrAIn asset preparation script; full originals remain available to zoom.
export const psytrainResponsiveMedia: Record<string, { srcSet: string; sizes: string }> = {
  "/v2-3/cases/psytrain/hero-counseling-scene.png": {
    "srcSet": "/v2-3/cases/psytrain/hero-counseling-scene-1280.webp 1280w, /v2-3/cases/psytrain/hero-counseling-scene-2560.webp 2560w, /v2-3/cases/psytrain/hero-counseling-scene-3840.webp 3840w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/research-mission-card-1.png": {
    "srcSet": "/v2-3/cases/psytrain/research-mission-card-1-640.webp 640w, /v2-3/cases/psytrain/research-mission-card-1-1280.webp 1280w, /v2-3/cases/psytrain/research-mission-card-1-1920.webp 1920w",
    "sizes": "(max-width: 1000px) 45vw, 27vw"
  },
  "/v2-3/cases/psytrain/research-mission-card-2.png": {
    "srcSet": "/v2-3/cases/psytrain/research-mission-card-2-640.webp 640w, /v2-3/cases/psytrain/research-mission-card-2-1280.webp 1280w, /v2-3/cases/psytrain/research-mission-card-2-1920.webp 1920w",
    "sizes": "(max-width: 1000px) 45vw, 27vw"
  },
  "/v2-3/cases/psytrain/research-roleplay-script.png": {
    "srcSet": "/v2-3/cases/psytrain/research-roleplay-script-640.webp 640w, /v2-3/cases/psytrain/research-roleplay-script-1280.webp 1280w, /v2-3/cases/psytrain/research-roleplay-script-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), 30vw"
  },
  "/v2-3/cases/psytrain/research-roleplay-peer.png": {
    "srcSet": "/v2-3/cases/psytrain/research-roleplay-peer-640.webp 640w, /v2-3/cases/psytrain/research-roleplay-peer-1280.webp 1280w, /v2-3/cases/psytrain/research-roleplay-peer-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), 30vw"
  },
  "/v2-3/cases/psytrain/research-roleplay-feedback.png": {
    "srcSet": "/v2-3/cases/psytrain/research-roleplay-feedback-640.webp 640w, /v2-3/cases/psytrain/research-roleplay-feedback-1280.webp 1280w, /v2-3/cases/psytrain/research-roleplay-feedback-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), 30vw"
  },
  "/v2-3/cases/psytrain/research-painpoint-feedback.png": {
    "srcSet": "/v2-3/cases/psytrain/research-painpoint-feedback-640.webp 640w, /v2-3/cases/psytrain/research-painpoint-feedback-1280.webp 1280w, /v2-3/cases/psytrain/research-painpoint-feedback-1920.webp 1920w",
    "sizes": "100px"
  },
  "/v2-3/cases/psytrain/research-painpoint-scenarios.png": {
    "srcSet": "/v2-3/cases/psytrain/research-painpoint-scenarios-640.webp 640w, /v2-3/cases/psytrain/research-painpoint-scenarios-1280.webp 1280w, /v2-3/cases/psytrain/research-painpoint-scenarios-1920.webp 1920w",
    "sizes": "100px"
  },
  "/v2-3/cases/psytrain/research-painpoint-growth.png": {
    "srcSet": "/v2-3/cases/psytrain/research-painpoint-growth-640.webp 640w, /v2-3/cases/psytrain/research-painpoint-growth-1280.webp 1280w, /v2-3/cases/psytrain/research-painpoint-growth-1920.webp 1920w",
    "sizes": "100px"
  },
  "/v2-3/cases/psytrain/research-painpoint-safety.png": {
    "srcSet": "/v2-3/cases/psytrain/research-painpoint-safety-640.webp 640w, /v2-3/cases/psytrain/research-painpoint-safety-1280.webp 1280w, /v2-3/cases/psytrain/research-painpoint-safety-1920.webp 1920w",
    "sizes": "100px"
  },
  "/v2-3/cases/psytrain/research-competitor-wysa.png": {
    "srcSet": "/v2-3/cases/psytrain/research-competitor-wysa-640.webp 640w, /v2-3/cases/psytrain/research-competitor-wysa-1280.webp 1280w, /v2-3/cases/psytrain/research-competitor-wysa-1500.webp 1500w",
    "sizes": "(max-width: 760px) 43vw, 22vw"
  },
  "/v2-3/cases/psytrain/research-competitor-replika.jpeg": {
    "srcSet": "/v2-3/cases/psytrain/research-competitor-replika-640.webp 640w, /v2-3/cases/psytrain/research-competitor-replika-1200.webp 1200w",
    "sizes": "(max-width: 760px) 43vw, 22vw"
  },
  "/v2-3/cases/psytrain/research-competitor-youper.png": {
    "srcSet": "/v2-3/cases/psytrain/research-competitor-youper-640.webp 640w, /v2-3/cases/psytrain/research-competitor-youper-1280.webp 1280w, /v2-3/cases/psytrain/research-competitor-youper-1920.webp 1920w",
    "sizes": "(max-width: 760px) 43vw, 22vw"
  },
  "/v2-3/cases/psytrain/system-brainstorm-transparent.png": {
    "srcSet": "/v2-3/cases/psytrain/system-brainstorm-transparent-640.webp 640w, /v2-3/cases/psytrain/system-brainstorm-transparent-1280.webp 1280w, /v2-3/cases/psytrain/system-brainstorm-transparent-1609.webp 1609w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/system-ideation-landing.png": {
    "srcSet": "/v2-3/cases/psytrain/system-ideation-landing-640.webp 640w, /v2-3/cases/psytrain/system-ideation-landing-1280.webp 1280w, /v2-3/cases/psytrain/system-ideation-landing-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/system-ideation-conversation.png": {
    "srcSet": "/v2-3/cases/psytrain/system-ideation-conversation-640.webp 640w, /v2-3/cases/psytrain/system-ideation-conversation-1280.webp 1280w, /v2-3/cases/psytrain/system-ideation-conversation-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/system-ideation-result.png": {
    "srcSet": "/v2-3/cases/psytrain/system-ideation-result-640.webp 640w, /v2-3/cases/psytrain/system-ideation-result-1280.webp 1280w, /v2-3/cases/psytrain/system-ideation-result-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/system-avatar-rationale-complete.png": {
    "srcSet": "/v2-3/cases/psytrain/system-avatar-rationale-complete-640.webp 640w, /v2-3/cases/psytrain/system-avatar-rationale-complete-1036.webp 1036w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  },
  "/v2-3/cases/psytrain/ui-landing-screen.png": {
    "srcSet": "/v2-3/cases/psytrain/ui-landing-screen-640.webp 640w, /v2-3/cases/psytrain/ui-landing-screen-1280.webp 1280w, /v2-3/cases/psytrain/ui-landing-screen-1920.webp 1920w",
    "sizes": "(max-width: 1000px) calc(100vw - 44px), 54vw"
  },
  "/v2-3/cases/psytrain/ui-training-screen.png": {
    "srcSet": "/v2-3/cases/psytrain/ui-training-screen-640.webp 640w, /v2-3/cases/psytrain/ui-training-screen-1280.webp 1280w, /v2-3/cases/psytrain/ui-training-screen-1920.webp 1920w",
    "sizes": "(max-width: 1000px) calc(100vw - 44px), 54vw"
  },
  "/v2-3/cases/psytrain/ui-result-screen.png": {
    "srcSet": "/v2-3/cases/psytrain/ui-result-screen-640.webp 640w, /v2-3/cases/psytrain/ui-result-screen-1280.webp 1280w, /v2-3/cases/psytrain/ui-result-screen-1920.webp 1920w",
    "sizes": "(max-width: 1000px) calc(100vw - 44px), 54vw"
  },
  "/v2-3/cases/psytrain/ui-live-emotion-avatar.png": {
    "srcSet": "/v2-3/cases/psytrain/ui-live-emotion-avatar-640.webp 640w, /v2-3/cases/psytrain/ui-live-emotion-avatar-1280.webp 1280w, /v2-3/cases/psytrain/ui-live-emotion-avatar-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(50vw - 30px), (max-width: 1000px) 30vw, 23vw"
  },
  "/v2-3/cases/psytrain/avatar-ai-logic-themed.png": {
    "srcSet": "/v2-3/cases/psytrain/avatar-ai-logic-themed-640.webp 640w, /v2-3/cases/psytrain/avatar-ai-logic-themed-1280.webp 1280w, /v2-3/cases/psytrain/avatar-ai-logic-themed-1920.webp 1920w",
    "sizes": "(max-width: 760px) calc(100vw - 44px), (max-width: 1000px) calc(100vw - 64px), 80vw"
  }
};
